import{a as l,S as u,i as n}from"./assets/vendor-D1AWmRWP.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const f="55660188-792f1fef602df37d72b3dd925";function d(s){return l.get("https://pixabay.com/api/",{params:{key:f,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(t=>t.data)}const c=document.querySelector(".gallery"),m=new u(".gallery a");function y(s){const t=s.map(o=>`
    <li class="gallery-item">
      <a href="${o.largeImageURL}">
        <img src="${o.webformatURL}" alt="${o.tags}" />
      </a>
      <p>❤️ ${o.likes}</p>
    </li>
  `).join("");c.insertAdjacentHTML("beforeend",t),m.refresh()}function h(){c.innerHTML=""}function p(){document.querySelector(".loader").classList.add("visible")}function g(){document.querySelector(".loader").classList.remove("visible")}const L=document.querySelector(".form");L.addEventListener("submit",b);function b(s){s.preventDefault();const t=s.target.elements["search-text"].value.trim();if(!t){n.error({message:"Введи щось для пошуку!"});return}h(),p(),d(t).then(o=>{if(o.hits.length===0){n.error({message:"Sorry, there are no images matching your search query."});return}y(o.hits)}).catch(()=>{n.error({message:"Помилка запиту 😢"})}).finally(()=>{g()})}
//# sourceMappingURL=index.js.map
